cc_library(
    name = "_pywrap_profiler_plugin",
    srcs = [],
    hdrs = ["pywrap_profiler_plugin.h"],
    deps = [
        "@org_profiler//internal:_pywrap_profiler_plugin",
    ],
    visibility = ["//visibility:public"],
)
