cc_library(
    name = "_pywrap_profiler_plugin",
    srcs = ["pywrap_profiler_plugin.cc"],
    hdrs = ["pywrap_profiler_plugin.h"],
    deps = [
        "@org_tensorflow//tensorflow/core/profiler/convert:convert_lib",
    ],
    visibility = ["//visibility:public"],
)
